### ISSUE TITLE
Using marked Renderer

### ISSUE THREAD

**Issue by DavidBiesack** [jstransformers/jstransformer-marked#15]
Is there any way to configure the [Renderer](https://github.com/markedjs/marked/blob/master/docs/USING_PRO.md) for `marked` -- for example, if I want to add CSS styles to certain elements (such as Bootstrap class="table" to GFM markdown tables)?

**Comment by ForbesLindesay** [comment]
This library passes options down to marked, so you can use all the options marked supports: https://marked.js.org/#/USING_ADVANCED.md#options
